//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReactMaterialUIShowcaseApi.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ReactMaterialUIShowcaseApi.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment content not found.
        /// </summary>
        public static string AttachmentContentNotFound {
            get {
                return ResourceManager.GetString("AttachmentContentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment not found.
        /// </summary>
        public static string AttachmentNotFound {
            get {
                return ResourceManager.GetString("AttachmentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract code cannot be over 32 characters.
        /// </summary>
        public static string ContractCodeMaxLength {
            get {
                return ResourceManager.GetString("ContractCodeMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract not found.
        /// </summary>
        public static string ContractNotFound {
            get {
                return ResourceManager.GetString("ContractNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deliverable ID mismatch.
        /// </summary>
        public static string DeliverableIdMismatch {
            get {
                return ResourceManager.GetString("DeliverableIdMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The deliverableId query parameter is required..
        /// </summary>
        public static string DeliverableIdQueryParameterRequired {
            get {
                return ResourceManager.GetString("DeliverableIdQueryParameterRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deliverable not found.
        /// </summary>
        public static string DeliverableNotFound {
            get {
                return ResourceManager.GetString("DeliverableNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deliverable type code cannot be over 5 digits.
        /// </summary>
        public static string DeliverableTypeCodeMaxLength {
            get {
                return ResourceManager.GetString("DeliverableTypeCodeMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deliverable type code must be numeric..
        /// </summary>
        public static string DeliverableTypeCodeNumeric {
            get {
                return ResourceManager.GetString("DeliverableTypeCodeNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designate email must be a valid email address (someuser@someserver.com).
        /// </summary>
        public static string DesignateEmailInvalid {
            get {
                return ResourceManager.GetString("DesignateEmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designate email cannot be over 100 characters.
        /// </summary>
        public static string DesignateEmailMaxLength {
            get {
                return ResourceManager.GetString("DesignateEmailMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designate cannot be over 100 characters.
        /// </summary>
        public static string DesignateMaxLength {
            get {
                return ResourceManager.GetString("DesignateMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designate phone must be a valid phone number (123-456-7890).
        /// </summary>
        public static string DesignatePhoneInvalid {
            get {
                return ResourceManager.GetString("DesignatePhoneInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designate phone cannot be over 30 characters.
        /// </summary>
        public static string DesignatePhoneMaxLength {
            get {
                return ResourceManager.GetString("DesignatePhoneMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is required..
        /// </summary>
        public static string FileRequired {
            get {
                return ResourceManager.GetString("FileRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File type not allowed.
        /// </summary>
        public static string FileTypeNotAllowed {
            get {
                return ResourceManager.GetString("FileTypeNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiscal year code cannot be over 8 characters.
        /// </summary>
        public static string FiscalYearCodeMaxLength {
            get {
                return ResourceManager.GetString("FiscalYearCodeMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiscal year code must be numeric..
        /// </summary>
        public static string FiscalYearCodeNumeric {
            get {
                return ResourceManager.GetString("FiscalYearCodeNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while processing your request..
        /// </summary>
        public static string GenericProcessingError {
            get {
                return ResourceManager.GetString("GenericProcessingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while processing your request..
        /// </summary>
        public static string GenericServerError {
            get {
                return ResourceManager.GetString("GenericServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid access token or refresh token.
        /// </summary>
        public static string InvalidAccessOrRefreshToken {
            get {
                return ResourceManager.GetString("InvalidAccessOrRefreshToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid client request.
        /// </summary>
        public static string InvalidClientRequest {
            get {
                return ResourceManager.GetString("InvalidClientRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid or expired refresh token.
        /// </summary>
        public static string InvalidOrExpiredRefreshToken {
            get {
                return ResourceManager.GetString("InvalidOrExpiredRefreshToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language must be 1 for English or 2 for French. 0 will default to English.
        /// </summary>
        public static string LanguageInvalid {
            get {
                return ResourceManager.GetString("LanguageInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lease code cannot be over 8 characters.
        /// </summary>
        public static string LeaseCodeMaxLength {
            get {
                return ResourceManager.GetString("LeaseCodeMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged out and refresh token invalidated..
        /// </summary>
        public static string LoggedOutAndRefreshTokenInvalidated {
            get {
                return ResourceManager.GetString("LoggedOutAndRefreshTokenInvalidated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month Id must be between 1 and 12..
        /// </summary>
        public static string MonthIdRange {
            get {
                return ResourceManager.GetString("MonthIdRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password cannot be over 50 characters.
        /// </summary>
        public static string PasswordMaxLength {
            get {
                return ResourceManager.GetString("PasswordMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be 8 characters.
        /// </summary>
        public static string PasswordMinLength {
            get {
                return ResourceManager.GetString("PasswordMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portfolio code cannot be over 5 characters.
        /// </summary>
        public static string PortfolioCodeMaxLength {
            get {
                return ResourceManager.GetString("PortfolioCodeMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary building code cannot be over 32 characters.
        /// </summary>
        public static string PrimaryBuildingCodeMaxLength {
            get {
                return ResourceManager.GetString("PrimaryBuildingCodeMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project code cannot be over 13 characters.
        /// </summary>
        public static string ProjectCodeMaxLength {
            get {
                return ResourceManager.GetString("ProjectCodeMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh token is required..
        /// </summary>
        public static string RefreshTokenRequired {
            get {
                return ResourceManager.GetString("RefreshTokenRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request body is required..
        /// </summary>
        public static string RequestBodyRequired {
            get {
                return ResourceManager.GetString("RequestBodyRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary building code cannot be over 32 characters.
        /// </summary>
        public static string SecondaryBuildingCodeMaxLength {
            get {
                return ResourceManager.GetString("SecondaryBuildingCodeMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred while updating the deliverable..
        /// </summary>
        public static string UnexpectedUpdateError {
            get {
                return ResourceManager.GetString("UnexpectedUpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username cannot be over 30 characters.
        /// </summary>
        public static string UsernameMaxLength {
            get {
                return ResourceManager.GetString("UsernameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username must be 8 characters.
        /// </summary>
        public static string UsernameMinLength {
            get {
                return ResourceManager.GetString("UsernameMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
    }
}
